package io.legacypilot.tool.spi;

public enum ToolErrorCode {
  UNREGISTERED_TOOL,
  INVALID_INPUT_SCHEMA,
  INVALID_OUTPUT_SCHEMA,
  INPUT_TOO_LARGE,
  OUTPUT_TOO_LARGE,
  POLICY_DENIED,
  APPROVAL_REQUIRED,
  TIMEOUT,
  PATH_VIOLATION,
  PATCH_CONFLICT,
  COMMAND_FAILED,
  INTERNAL_ERROR
}
